# Generated by Django 3.2.4 on 2021-06-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_participant_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='skills',
            field=models.ManyToManyField(blank=True, to='general.Skill'),
        ),
    ]
