# Generated by Django 3.2.4 on 2021-06-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_participant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=265, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/competitions')),
                ('participants', models.ManyToManyField(blank=True, to='general.Participant')),
                ('skills', models.ManyToManyField(blank=True, to='general.Skill')),
            ],
        ),
    ]
