# Generated by Django 3.2.4 on 2021-06-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_alter_qualification_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='title',
            field=models.CharField(default='Web Developer', max_length=265),
        ),
    ]
